name: oci-resource-manager-build-demo
on:
  push:
    branches:
      - main
jobs:
  build-resource-manager:
    name: Test StackSpot Plugin
    runs-on: ubuntu-latest
    env: 
        REGION: "sa-santiago-1"
    steps:
      
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Write Config & Key Files'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem

      - name: 'Install OCI CLI'
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL

      - name: 'Install StackSpot CLI'
        run: | 
          curl -L -O https://stk.stackspot.com/installer/linux/stk.deb
          sudo dpkg --install stk.deb
          test -f ~/.stk/bin/.bash_profile && . ~/.stk/bin/.bash_profile
          stk -v


      - name: 'Fix OCI Config File Permissions'
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/key.pem
